insecure = true
port = 26257
http-port = 8080

# https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#cache-and-sql-memory-size
# as a percentage of total memory
cache = ".25"
max-sql-memory = ".25"

[locality]
region = "default"
datacenter = "default"

# We need to use pre-canned certs, at least until this becomes a reality:
#   https://github.com/habitat-sh/habitat/issues/4091
#
# WARNING: Change these before deploying to a real server!!!
# to generate, see: https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html
# then set insecure to false to use mutual TLS authentication
[certs]
ca_cert = """
-----BEGIN CERTIFICATE-----
MIIDBjCCAe6gAwIBAgIQJJdxRBnJLmNdJssGNzWGeTANBgkqhkiG9w0BAQsFADAr
MRIwEAYDVQQKEwlDb2Nrcm9hY2gxFTATBgNVBAMTDENvY2tyb2FjaCBDQTAeFw0x
ODEwMTYyMTM0NTJaFw0yODEwMjQyMTM0NTJaMCsxEjAQBgNVBAoTCUNvY2tyb2Fj
aDEVMBMGA1UEAxMMQ29ja3JvYWNoIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAohh2ddPCaH5cEn/PC7Fgt2qN2Wki5Ph/lh/8lMU8A7+d/ihjQ/Kn
rJ7acAJBRI+oBvzJpOA9zGn984OnYAvzTglkWipZHvwyPexJDWwK1IhvxKc+4tPX
urGoLmpWUsVCrkIDsPJw9WUBGHehyGIdYLD75lLIrW7aGr3LIU/TIdn6DUFNnIFm
KvhWf5WK8ROQpZeg73hr/LLgIghQA1nHxkotKmYaxduB8yiEy5fC3LRljd5ZzkYD
UvI6AJtc1kBKXJ1/CsGsr0HGyFUeDgjS6HqIgoApXz+zAQKndFx1yqIY9+yMCbPQ
nLXV3BgeAkrx927jghrRw5ArYuwM0haLgwIDAQABoyYwJDAOBgNVHQ8BAf8EBAMC
AuQwEgYDVR0TAQH/BAgwBgEB/wIBATANBgkqhkiG9w0BAQsFAAOCAQEAPv4lGZ7Q
l8cJYFZCeKSs4tjKOILIovGqjA4g17BFL0Ku3DAo9+oiqKQ/pJmUe3PzS9oiL/HX
CYvZwnqSdH5QRLruNA6fTkH9vgzJW8UP0bqMWs4Zzy4nLyGlQNlxei8YQDDkPSz5
jPLTvCfVp059nBMa88OAZjip+dvbCNmKi4ml3PrRu1gtjGJwu1IEZ3Tnq5u93auz
0Kx0bDWGYxxDgiB/WjGzwLpG+ueNs7mRZDc/icMG5yhXK2JTWepESdibD0Wj3CMZ
TE/DBaugkC78cLLYlUg70vdVxAFA0k9yNpCEmufO7TIoAPI/UubJmbpWgK2JbA4q
bAfw+bbGOA+s/A==
-----END CERTIFICATE-----
"""

ca_key = """
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAohh2ddPCaH5cEn/PC7Fgt2qN2Wki5Ph/lh/8lMU8A7+d/ihj
Q/KnrJ7acAJBRI+oBvzJpOA9zGn984OnYAvzTglkWipZHvwyPexJDWwK1IhvxKc+
4tPXurGoLmpWUsVCrkIDsPJw9WUBGHehyGIdYLD75lLIrW7aGr3LIU/TIdn6DUFN
nIFmKvhWf5WK8ROQpZeg73hr/LLgIghQA1nHxkotKmYaxduB8yiEy5fC3LRljd5Z
zkYDUvI6AJtc1kBKXJ1/CsGsr0HGyFUeDgjS6HqIgoApXz+zAQKndFx1yqIY9+yM
CbPQnLXV3BgeAkrx927jghrRw5ArYuwM0haLgwIDAQABAoIBADJ+SlBz8YhZbFb6
50UuMQGRuLQz8wG+gwgB2M2DDynfw9iLPjjJWwADz+m6WhiAY4ghsLKig72sesYj
ibz6nAUAGfmYXYCwcPonI66BrHH+OkrZClbgRMBMXSZwS4mnFxlvSPUS4KsglpHH
mmbwYVRgbWeW/BpCgMB5xNAQrKVLYYu9KAVOs1PPDHQGUxvUNGrvHcUiFAa7qFpQ
+3iuU4YUHIaZO+nqDUI/9jxCRYuyEC0RhTWszxAqQJX3DaRySgzTRUnCCFdfS8k/
nu/U/qtAxW0WgwhlWEi5hK2KWSxn4L0/O4GP11v9hKS9l5Kz+rnscVBPurkgi0TB
uAGK/2kCgYEAxoAvzldnhfIA2DH421kbB8iyAdi3lucxdsOkuyC6fYVrPxH2b4+S
6zqeHRU6MI7djbWMnctjUK2/wiuxpbPdh4e4Z37IdqPXeyOWpIHhDT5vV6TyCR/3
nqMeDEmTsvFjw31rM9X5h6UMCKfMwtejX15QhnwP89DkVGqPbXY4DWcCgYEA0Qym
6XBHczhfaEt+4IwN2WRIUDkTmwbwL+Yto1XXJvyFXP0QmSC3LNGHmkhY9ZUB60FE
xv5iLkNR7v6jK9+jJY5XipLxC+Sr+hpZhu8u2dAFcGs+PvVUYpbTfy10cnWDigs3
Av8oDzYTTbJEJ4LwvKuc2W8c5haLVOQcNWG5o4UCgYBCyrdLUxW+eGPYW1hFVoJF
6D4daPK9kCWQtNwlKyoVOmOP4VduynzBMgQp/Q6LcEcUe9ZI8jsE1rIDf/hSrWcJ
R53BFWQWp6LGCH+T8y/q6OtGLnZSo7MKahCeSdOtDpRnHziHRKSmA988ulmn5i9O
08l8txoXDF8IGKMSTgkmWQKBgQCwUAVumT4J1Z/SLOpjpHwBv+yljJ4WgHGPVIll
Wv7NaOlqFh4rqEYVzNqbqy0sY3Js4m2Jj/9qmWi/M5CXblUBVd5Lh8c5irHpjNO5
VH2lQydzO2ASZYO4axESEFpINwisIu1Q37b/rVH2k8WbtXopBmyRjn9HJ/h3rrSD
6VpSqQKBgQC6sxEtn6Tvx9HVoMfKqbftidNuLClFZOwf/wZ4VUPdRcje33g7DnWR
QF6nou4yVGxpuc6mKcmCI6TXlc1PyX/JqFn7f8OxE0ZYrLXGKfwY6Chlz4rVQNrQ
u25o3656RMqGHiLxHMhUFhZjsJtKkGzq23b7s2NWxBF7kUwhyMuNjA==
-----END RSA PRIVATE KEY-----
"""

root_cert = """
-----BEGIN CERTIFICATE-----
MIIDADCCAeigAwIBAgIRAMXWDkxbPuIGcBisj+noYpEwDQYJKoZIhvcNAQELBQAw
KzESMBAGA1UEChMJQ29ja3JvYWNoMRUwEwYDVQQDEwxDb2Nrcm9hY2ggQ0EwHhcN
MTgxMDE2MjEzNjMyWhcNMjMxMDIxMjEzNjMyWjAjMRIwEAYDVQQKEwlDb2Nrcm9h
Y2gxDTALBgNVBAMTBHJvb3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDZ+I8N42IIqBs5Nve7InqKUnQb8vYPDcC3ZESuqHSCC0nVpik7GC3/hDUTWdIM
GjcsVxC3ZGJhmiVIbycA4RvlHfcGsIYLspvah7unFtq7Gt/wVv4xql/HCMAmX7xG
p0ywQZcE+BPuRDjAvPh6TyTa9O5uS6nETWIyLECNOQZ/DJJVY1QN8ptLnfEKXvPh
mHj5+oED3HQjDX/HEnXnLtHr84pv82NNZ0U0WECETzKN1P+fUiLBHoDXmEV55hOn
cXLNiO+wUeXvvmn5wMeB64w/W/qY6NGcG4NTfQAvsEKq8JH4YdHbzegbFQa3x+6N
PhtfY3hTPCap3FOB54wwP9hhAgMBAAGjJzAlMA4GA1UdDwEB/wQEAwIFoDATBgNV
HSUEDDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAIljD/e3TkNN9mjcn
EnVS5jls8OWyDCU/R/zDPh3qJdxCctqIsggkL1OHXS3eiLcDjsS+At6Yfpzm5KuN
Gwf9726MxYsqJ68SSjFWqLAUqVrf7XeGFrSajxPL8IP2RkuFG8i1bMK/hS/rT33Y
Tme4SNbBeOCyD3J98aJ7NWett3CgyeNVUr7X0mCHS0LxXHrp7ffSJdiWm2+3x+cT
4ln1UOiN0sOaJo6C4lmi5pYtkZFbBLf1rWTNQ6lvN63NCQFa2d6/6SfRUfA6OEYN
nVPIwD9uDXPLyMzNqQ4XaeiyBIh2KG+wMerk9aIfQDrfpDO8nJpD0nu76TQljauB
s9UITg==
-----END CERTIFICATE-----
"""

root_key = """
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2fiPDeNiCKgbOTb3uyJ6ilJ0G/L2Dw3At2RErqh0ggtJ1aYp
Oxgt/4Q1E1nSDBo3LFcQt2RiYZolSG8nAOEb5R33BrCGC7Kb2oe7pxbauxrf8Fb+
MapfxwjAJl+8RqdMsEGXBPgT7kQ4wLz4ek8k2vTubkupxE1iMixAjTkGfwySVWNU
DfKbS53xCl7z4Zh4+fqBA9x0Iw1/xxJ15y7R6/OKb/NjTWdFNFhAhE8yjdT/n1Ii
wR6A15hFeeYTp3FyzYjvsFHl775p+cDHgeuMP1v6mOjRnBuDU30AL7BCqvCR+GHR
283oGxUGt8fujT4bX2N4UzwmqdxTgeeMMD/YYQIDAQABAoIBAQC/ml/d3HhLlcJA
fBIuHLPNLYfFHcCwIO28B9bcFVY9DkE8HlD2El400vl45ibe3piLUIlwPDzDASYu
0w5dFoRX1gxUhA2A8ONRqKkKyutBN/GMKlxOOi7xHb8SvGsbTGr8MNvY0V1rv+qH
elWN5k5GbrG8oKQ926wq4H1p5qvQNxSKW7jPeWFi7YdgH+Y5bgOvqpPqJjNKCXdN
bI/DOfqy7RBL0xj47/oGbbRpKXvA/MIaEQQFQ5Nu0rcpmezpv3AFYb2x8g/d9JCq
YYpunPimgZUl/iS7eDWjrw2RB3DPy7EWxyDBzh+dxaUCuJdjm1obrkuK9kCPrUln
8n8Y8VAlAoGBAOzzlBUl4kqwCmYLfUJWlqIp4kQhi9n7d8GuS1F++V+uttiKHkiG
czXNG6iKSvAuh/92Sqmw+Wq8TrOua1gqQXu4/axTHDUanwYV+JmKpx5Z6u87gSGe
yFLcBiB8If8/aJiF4eDOchTONgbiFBfm+t8I2cs8mKlxu4Vd5GVMAa13AoGBAOt+
XSo/I17LlSHpT3hqyNRpBCrSSAKsziHa4s3BP9TlM/iJP+XP295Z8lbc6jyuoyEF
x+VSCeDtLIZ1GfaGk1CqxBpRjgrPOnDkdf9nUbFVHc477K1CJCEojbj0ukwUcdqb
BXgv2gM/sbfwDkJo1nwtQzA47E55y0s1f7gLcr7nAoGAZsZ38nxOHOsid4SAPifk
ik30cGzEhjYGiaGZ1a1naNMVR/MQk5CNpEZkusPRIUBtiKa8V8IFTQCEencq5EDf
ylRA41/hGj+DvlYFUEPNnOKPflim9/gxF4+LsMdmz5mnOpDHmoSxAsk2seGZqYxs
QBVMslSEOuqz1XMWP8Gp8J0CgYA2tiL6/7Q9/9pkCIp4FYcXIlbfg/9K787sOqha
2Tz1P1L1uR1pTQNuA0O0PpsFAiXQNEGe25KD+VZQ3r/rcJSlNydcXfo8NK0FMW7g
qaZnJrlIAtAX6LfwJDXY9LKbnlxdR4rbw3JJMvEdJN6LO0QpkXJ8r5znFpDOpl1H
6xD7nQKBgQCc0NGL8RZAQuDPQf5gC/BUpTBRlVf/Tqo/4apoBk66ixcXPumSHsDP
6Ctefhze0gZTuIqCT4t5OfHdTnRX7VsAJ/I0wk/i0yTulx1c6lauweJ2LQZbDW+F
f0IgvthmqyCefDz388JbZ2+eGZMTAZyEO2+zCWE0qqXo5oKZQAZDiw==
-----END RSA PRIVATE KEY-----
"""
