---
project:
  alias: core-plans-refresh-2021q2

github:
  delete_branch_on_merge: true

subscriptions:
  - workload: pull_request_opened:{{agent_id}}:*
    actions:
      - post_github_comment:.expeditor/templates/welcome.mustache:
          ignore_team_members:
            - habitat-sh/habitat-core-maintainers
            - habitat-sh/habitat-core-plans-maintainers

pipelines:
  - verify:
      public: true
      definition: .expeditor/generate_verify_pipeline.sh
