# switch this to false you want to start in DEVMODE
# https://www.vaultproject.io/intro/getting-started/dev-server.html
[dev]
### Developer mode Overides settings in bacvkend and uses in memory setting.
## True = on, false = off
mode = false

[backend.type]
### Set storage backend type, and then configure below.
## Options: inmem, filesystem, consul, dynamodb.
## Only uncomment the one corrisponding to the configuration below.
inmem = true
#consul = true
#file = true
#consul = true
#dynamodb = true

[backend]
### Storage backends. Uncomment method and associate attributes required
## DEFAULT - DEVMODE/IN MEMORY
storage = "inmem"

### FILE/FILESYSTEM
#storage = "file"
## Location to store data:
#storage_file_path = "/path/to/vault/data"

### CONSUL
#storage = "consul"
#address = "FQDNorIP:PORT"
#path = "consulPath"

### DYNAMDODB
#storage = "dynamodb"
#endpoint = ""
#ha_enabled = "false"
#max_parallel = "128"
#region = "us-west-2"
#read_capacity = 5

## REQUIRED: DynamoDB table name.
#table = "vault-dynamodb-backend"
#write_capacity = 5

### AWS Access
## REQUIRED: Access key and secret to connect and create DynamoDB, if database does not exist.
#access_key = ""
#secret_key = ""
#session_token = ""

[listener]
type = "tcp"
location = "127.0.0.1"
port = "8200"
tls_disable = "1"
