#                 _   _  __           _                     _____
#      /\        | | (_)/ _|         | |                   |  __ \
#     /  \   _ __| |_ _| |_ __ _  ___| |_ ___  _ __ _   _  | |__) | __ ___
#    / /\ \ | '__| __| |  _/ _` |/ __| __/ _ \| '__| | | | |  ___/ '__/ _ \
#   / ____ \| |  | |_| | || (_| | (__| || (_) | |  | |_| | | |   | | | (_) |
#  /_/    \_\_|   \__|_|_| \__,_|\___|\__\___/|_|   \__, | |_|   |_|  \___/
#                                                    __/ |
#                                                   |___/

#A valid license key is needed for this application to start correctly
license = ""
port = 8081

[database]

type   = "derby"
url    = "jdbc:derby:{db.home};create=true"
driver = "org.apache.derby.jdbc.EmbeddedDriver"

[storage]

binary_provider_type       = "file-system"
binary_provider_cache_size = "5000000000"

[jvm]
min_heap = "512m"
max_heap = "2g"
